<?php

namespace ErposBundle\Repository;

/**
 * tbl_taxeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tbl_taxeRepository extends \Doctrine\ORM\EntityRepository
{
}
